import { ApolloProvider } from "@parknest/network/src/config/apollo";
import { Container } from "@parknest/ui/app/components/atoms/Container";
import { SessionProvider } from "@parknest/ui/app/components/molecules/SessionProvider";
import { ToastContainer } from "@parknest/ui/app/components/molecules/Toast";
import { Header } from "@parknest/ui/app/components/organisms/Header";
import "@parknest/ui/app/globals.css";
import { MenuItem } from "@parknest/util/types";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Parknest",
  description: "Generated by create next app",
};

const MENUITEMS: MenuItem[] = [
  { label: "Search", href: "/search" },
  { label: "Bookings", href: "/bookings" },
  { label: "About", href: "/about" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-25`}
          >
            <Header menuItems={MENUITEMS} />
            <Container>{children}</Container>
            <ToastContainer />
          </body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  );
}
