name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Full CI/CD Process
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma Client
        run: yarn postinstall

      - name: Wait for PostgreSQL to be ready
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          until pg_isready; do
            echo "Waiting for PostgreSQL...";
            sleep 2;
          done

      - name: Apply Database Migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
        run: npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma

      - name: Build Project
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3000
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
        run: yarn build

      - name: Check Formatting with Prettier
        run: yarn format

      - name: Check Linting with ESLint
        run: yarn lint

      - name: Type Check with TypeScript
        run: yarn tsc
